[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
btclib = { path = "../lib" }
clap = { version = "4.5.21", features = ["derive"] }
flume = "0.11.1"
tokio = { version = "1.41.1", features = ["full"] }
